### ISSUE TITLE
コーディング規約作成

### ISSUE THREAD

**Issue by archangel913** [archangel913/DBotHub#1]
# 【コーディング規約】
c#の場合、.editorconfigファイルを作るので、それに従う。

# 【ブランチ名】
**prefix/[isuue]** で命名する。
例) fix/#10000

|prefix|意味|
|----|----|
|feature|機能追加|
|ref|リファクタリング|
|fix|バグ修正|

# 【コミットメッセージ】
**[絵文字][任意のメッセージ]** で書く。
例) 👍Improve the user interface in the management view.

|絵文字|意味|
|----|----|
|:+1:| `:+1:` 機能の改善|
|:arrow_double_down: | `:arrow_double_down:` 機能追加|
|:bug:| `:bug:` バグ修正|
|:recycle:| `:recycle:` リファクタリング|
|:book:| `:book:` ドキュメント作成|
|:hammer:| `:hammer:` 実装の準備|

**Comment by archangel913** [comment]
上記のは草案

逐次[コーディング規約](https://github.com/archangel913/DBotHub/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)に追記

**Comment by archangel913** [comment]
基本的な規約は完成したと思います。

@AutumnSky1010 　[コーディング規約](https://github.com/archangel913/DBotHub/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)を確認して、問題なさそうだと思ったら、このチケットをCloseしてください。

話し合いが必要だと思われる規約の変更が発生した場合、このチケットを再オープン or このチケットに関連させた新チケット作成、で対応しようと思います。

**Comment by AutumnSky1010** [comment]
問題ないと思います。
