### ISSUE TITLE
リポジトリの階層構造について

### ISSUE THREAD

**Issue by archangel913** [archangel913/DBotHub#4]
* doc: GitHub pages用
* src: コード用
など階層分けをする。

例: 
> DBotHub
> └ doc
> └ src
>   └ Main
>     └ Domain
>     └ Application
>   └ Test

**Comment by AutumnSky1010** [comment]
この構造だとdomainとかもsrcディレクトリ内のほうがいいかも？
DBotHub
└ doc
└ src
　└ Domain
　└ Application
└ Test

**Comment by archangel913** [comment]
ごめん、階層構造崩れてた。

> └ doc
> └ src
> 　└ Main
> 　　└ Domain
> 　　└ Application
> 　└ Test
> 　　└ TestDomain
> 　　└ TestApplication

名前空間はsrcをルートはどうでしょう

例: ```Main.Domain.MusicEntity```

**Comment by AutumnSky1010** [comment]
> ごめん、階層構造崩れてた。
> 
> > └ doc
> > └ src
> > 　└ Main
> > 　　└ Domain
> > 　　└ Application
> > 　└ Test
> > 　　└ TestDomain
> > 　　└ TestApplication
> 
> 名前空間はsrcをルートはどうでしょう
> 
> 例: ```Main.Domain.MusicEntity```

階層はそれでいいと思う。
名前空間はMain or DBotHubスタートがいいかも？

**Comment by AutumnSky1010** [comment]
`DBotHub.Main.Domain.MusicEntity` (1)
か
`DBotHub.Domain.MusicEntity` (2)
で悩んでる。

(1)の命名だと、テストは
`DBotHub.Test.Domain.TestMusicEntity`
みたいな命名になって、

(2)だと、
`DBotHub.TestDomain.TestMusicEntity`
みたいな命名になると思う。

**Comment by AutumnSky1010** [comment]
https://github.com/archangel913/DBotHub/pull/5

**Comment by archangel913** [comment]
## (1)
### メリット
階層に則っており、直感的にわかりやすい。

### デメリット
名前空間自体が冗長になりやすい。

## (2)
### メリット
製品の部品としてみた時、何の部品かがわかりやすい。

### デメリット
フォルダ階層に沿っていないのでファイルの物理的な位置がわからない。

# 

個人的には(2)の方がスマートかな。

DomainのテストはTestDomainで固定だろうし、名前空間の衝突もないと思う。

**Comment by AutumnSky1010** [comment]
個人的には(2)の方が好きかな

### 理由

- `[製品名].[プロジェクト名].[任意]`だけで十分情報が足りると思う。
- ディレクトリ構造に則らない部分はせいぜいTestとMainくらいだから何とかなると思ってる。

**Comment by archangel913** [comment]
了解した。

**Comment by archangel913** [comment]
マージ完了しました。

**Comment by AutumnSky1010** [comment]
あざざます
